name: CI

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      matrix:
        platform:
          - { name: Windows MSVC, os: windows-latest }
          - {
              name: Linux GCC,
              os: ubuntu-latest,
              flags: -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10,
            }
          - { name: MacOS Apple Clang, os: macos-latest }
          - {
              name: MacOS GCC,
              os: macos-latest,
              flags: -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11,
            }

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
      - name: Install Conan Package Manager
        run: pip install conan -U
      - name: Configure CMake
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./build ${{ matrix.platform.flags }}
      - name: Build
        shell: bash
        run: cmake --build ./build --config Release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ matrix.platform.name }}
          path: |
            ./build/src/shadowsocks-asio
            ./build/src/Release/shadowsocks-asio.exe
      - name: Test
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./build/test/Release/test_ssurl
            ./build/test/Release/test_ip_set
            ./build/test/Release/test_rule_set
          else
            ./build/test/test_ssurl
            ./build/test/test_ip_set
            ./build/test/test_rule_set
          fi
